version: "3"
services:
  # src: https://registry.hub.docker.com/_/caddy
  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    labels:
      hs__pod: support

  # docs: https://jellyfin.org/docs/general/administration/installing.html#docker
  # src: https://hub.docker.com/r/jellyfin/jellyfin
  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - /hs/jellyfin/config:/config
      - /hs/jellyfin/cache:/cache
      - /media:/media
    labels:
      hs__pod: jellyfin
