FROM nodered/node-red

RUN npm install \
  # https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket
  node-red-contrib-home-assistant-websocket \
  # https://flows.nodered.org/node/node-red-contrib-chronos
  node-red-contrib-chronos
